spring:
#  datasource:
#    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/tryout
#    dialect: org.hibernate.dialect.MySQL8Dialect
#    username: root
#    password: root
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    database: mysql
  master:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tryout
    dialect: org.hibernate.dialect.MySQL8Dialect
    username: root
    password: root
  slaves:
    - driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/tryout_slave1
      dialect: org.hibernate.dialect.MySQL8Dialect
      username: root
      password: root
    - driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/tryout_slave2
      dialect: org.hibernate.dialect.MySQL8Dialect
      username: root
      password: root


