spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    properties:
      hibernate:
        generate_statistics: false
        jdbc:
          batch_size: 4
        order_inserts: true
  datasource:
    url: jdbc:postgresql://localhost:5432/tryout
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres

  kafka:
    bootstrap-servers: localhost:29092,localhost:39092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'



#    consumer:
#      bootstrap-servers: localhost:29092,localhost:39092
#    producer:
#      bootstrap-servers: localhost:29092,localhost:39092

